### ISSUE TITLE
Add scripting capability

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#261]
Scripting myMPD function could be useful, e.g. for special timer actions. myMPD will get the option to be compiled with liblua to execute scripts.

- Scripts can be saved in the directory `/var/lib/mympd/scripts`
- One file per script with the extension `.lua`
- For the first version no script editor in the gui is planned
- For safety reasons scripts are default disabled

**Tasks**
- [x] scripts callable in main menu
- [x] add timer action for scripts
- [x] add script paramter to mympd-config
- [x] add embedded lua interpreter
- [x] scripts should have access to current myMPD and MPD state
- [x] scripts can call all myMPD API functions
- [x] scripts should have access to API function return values

Documentation in the wiki: https://github.com/jcorporation/myMPD/wiki/Scripting
