### ISSUE TITLE
Some UI Enhancements

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#474]
- [ ] actions per disc for multidisc albums (add/replace queue) #472
- [ ] display goto playing song button if current song is out of viewport #467
- [ ] improve display of current playing song in queue view #467
