### ISSUE TITLE
Add webradio feature 

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#502]
add a radio browser tab that utilises  the api from [radio-browser]( https://www.radio-browser.info/#/) 
that way you could search for radio streams rather than add singularly 

_Originally posted by @GreyMarvel in https://github.com/jcorporation/myMPD/discussions/492_

### Tasks

- [x] Implement search
- [x] Implement same actions as for streams
- [x] Use picture in playback card
- [x] Implement detail modal
- [x] Add backend proxy
- [x] Implement usage api
- [x] Webradio favorites
- [x] Add webradio favorites to homescreen
- [x] Queue customizations
- [x] Playback view customization
- [x] Integrate https://github.com/jcorporation/webradiodb
- [x] Add description field to metadata
- [x] Implement sorting 
- [x] Searchable selects for genre/country/language 
- [x] Improve radiobrowser search

**Comment by jcorporation** [comment]
Tasks:
- [ ] Implement search
- [ ] Implement same actions as for streams
- [ ] Use picture for homescreen
- [ ] Implement detail modal
